name: Eiffel.Framework.OnPush

on:
  push:
    branches: [ version-script-test ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0
        
    - name: Get previous commit SHA
      id: git
      run: echo "::set-output name=prev_sha::$(git rev-parse HEAD~1)"
     
    - name: Restore
      run: .\.build\restore.ps1 -commitSHA ${{ github.sha }} -prevSHA ${{ steps.git.outputs.prev_sha }}
      shell: powershell
      
    - name: Build
      run: .\.build\build.ps1 -commitSHA ${{ github.sha }} -prevSHA ${{ steps.git.outputs.prev_sha }}
      shell: powershell
      
    - name: Test
      run: .\.build\test.ps1 -commitSHA ${{ github.sha }} -prevSHA ${{ steps.git.outputs.prev_sha }}
      shell: powershell
      
    - name: Version
      run: |
        .\.build\version.ps1 -commitSHA ${{ github.sha }} -prevSHA ${{ steps.git.outputs.prev_sha }}
        git push
      shell: powershell